
server {
    listen 8000;
    server_name aross.studio;

    root /usr/share/nginx/html/root;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    error_page 404 /404.html;
    location = /40x.html { internal; }
}

server {
    listen 8000;
    server_name design.aross.studio;

    root /usr/share/nginx/html/design;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}

server {
    listen 8000;
    server_name portfolio.aross.studio;

    root /usr/share/nginx/html/portfolio;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}

server {
    listen 8000 default_server;
    server_name _;
    return 404;
}
